/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Carreras;


import Controlador.Compras.clsProveedor;
import Controlador.clsUsuarioConectado;

// 2. Importar clases de la capa Modelo 
import Modelo.Compras.ProveedorDAO;
import Modelo.BitacoraDAO;
import Modelo.PermisosDAO;

// 3. Importar librerías estándar de Java Swing
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.io.File;

import java.lang.Process;


import java.lang.Runtime;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import Modelo.Conexion;


/**
 *
 * @author 50240
 */
public class frmMantenimientoCarreras extends javax.swing.JFrame {

    /**
     * Creates new form frmMantenimientoCarreras
     */
    public frmMantenimientoCarreras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProNombre = new javax.swing.JTextField();
        txtProNit = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificarr = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO CARRERA", "NOMBRE CARRERA", "CODIGO FACULTAD", "ESTADO"
            }
        ));
        jScrollPane2.setViewportView(tablaProveedores);

        jLabel1.setText("CARRERAS");

        jLabel2.setText("CODIGO CARRERA:");

        jLabel3.setText("NOMBRE CARRERA:");

        jLabel4.setText("CODIGO FACULTAD:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificarr.setText("Modificar");
        btnModificarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarrActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText("ESTADO:");

        jButton6.setText("AYUDA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnSalida.setText("SALIR");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtProNit, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(txtProNombre))
                                    .addComponent(txtProCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(33, 33, 33)
                                .addComponent(jComboBox1, 0, 174, Short.MAX_VALUE)))
                        .addGap(87, 87, 87)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificarr)
                            .addComponent(btnEliminar)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiar))
                        .addGap(48, 48, 48))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtProCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtProNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarr))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtProNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6)
                                    .addComponent(btnSalida)
                                    .addComponent(btnReportes))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        // VALIDACIÓN DE PERMISO (Incluye Bypass Admin ID 1)
        if (!puedeInsertar()) {
            JOptionPane.showMessageDialog(null, "No posee permisos para registrar proveedores.");
            return;
        }

        clsProveedor proveedor = new clsProveedor();
        proveedor.setPronombre(txtProNombre.getText());
        proveedor.setPronit(txtProNit.getText());
        proveedor.setProcuentabancaria(txtProCuenta.getText());
        proveedor.setProcontacto(txtProContacto.getText());
        proveedor.setProdepartamento(txtProDepto.getText());
        proveedor.setProestado(jComboBox1.getSelectedItem().toString());

        if (proveedorDAO.ingresarProveedor(proveedor) > 0) {
            JOptionPane.showMessageDialog(null, "Proveedor Registrado con éxito");
            // Registro en bitácora con el ID del usuario actual
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Registró Proveedor");
            llenarTabla();
            limpiarCampos();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarrActionPerformed
        // VALIDACIÓN DE PERMISO (Incluye Bypass Admin ID 1)
        if (!puedeModificar()) {
            JOptionPane.showMessageDialog(null, "No posee permisos para modificar información.");
            return;
        }

        if (txtProCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe buscar primero un proveedor antes de modificarlo.");
            return;
        }

        clsProveedor proveedor = new clsProveedor();
        proveedor.setProcodigo(Integer.parseInt(txtProCodigo.getText()));
        proveedor.setPronombre(txtProNombre.getText());
        proveedor.setPronit(txtProNit.getText());
        proveedor.setProcuentabancaria(txtProCuenta.getText());
        proveedor.setProcontacto(txtProContacto.getText());
        proveedor.setProdepartamento(txtProDepto.getText());
        proveedor.setProestado(jComboBox1.getSelectedItem().toString());

        if (proveedorDAO.actualizaProveedor(proveedor) > 0) {
            JOptionPane.showMessageDialog(null, "Información actualizada correctamente");
            // Registro en bitácora
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Modificó Proveedor ID: " + txtProCodigo.getText());
            llenarTabla();
            limpiarCampos();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarrActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!puedeEliminar()) {
            JOptionPane.showMessageDialog(null, "No posee permisos para eliminar registros.");
            return;
        }

        if (txtProCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el código del proveedor que desea eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este proveedor?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacion == 0) {
            clsProveedor proveedor = new clsProveedor();
            proveedor.setProcodigo(Integer.parseInt(txtProCodigo.getText()));

            if (proveedorDAO.borrarProveedor(proveedor) > 0) {
                // Registro en bitácora si se eliminó con éxito
                bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Eliminó Proveedor ID: " + txtProCodigo.getText());
            }
            llenarTabla();
            limpiarCampos();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!puedeBuscar()) {
            JOptionPane.showMessageDialog(null, "No posee permisos para realizar búsquedas.");
            return;
        }

        if (txtProCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un código para buscar.");
            return;
        }

        clsProveedor proveedor = new clsProveedor();
        proveedor.setProcodigo(Integer.parseInt(txtProCodigo.getText()));
        proveedor = proveedorDAO.consultaProveedorPorId(proveedor);

        if (proveedor.getPronombre() != null) {
            txtProNombre.setText(proveedor.getPronombre());
            txtProNit.setText(proveedor.getPronit());
            txtProCuenta.setText(proveedor.getProcuentabancaria());
            txtProContacto.setText(proveedor.getProcontacto());
            txtProDepto.setText(proveedor.getProdepartamento());
            jComboBox1.setSelectedItem(proveedor.getProestado());

            // Registro en bitácora de la consulta realizada
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Buscó Proveedor ID: " + txtProCodigo.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Proveedor no encontrado");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // Buscar el archivo de ayuda en diferentes ubicaciones
            String[] rutasPosibles = {
                "AyudasCompras/AyudaComprasHelp.chm",
                "src/main/resources/AyudasCompras/AyudaComprasHelp.chm",
                "AyudaComprasHelp.chm"
            };

            File archivoAyuda = null;
            for (String ruta : rutasPosibles) {
                File temp = new File(ruta);
                if (temp.exists()) {
                    archivoAyuda = temp;
                    break;
                }
            }

            if (archivoAyuda != null && archivoAyuda.exists()) {
                // Para Windows
                if (System.getProperty("os.name").toLowerCase().contains("win")) {
                    Runtime.getRuntime().exec("hh.exe " + archivoAyuda.getAbsolutePath());
                } else {
                    // Para otros sistemas operativos
                    Runtime.getRuntime().exec("xdg-open " + archivoAyuda.getAbsolutePath());
                }
                System.out.println("Ayuda abierta correctamente");
            } else {
                JOptionPane.showMessageDialog(this,
                    "El archivo de ayuda no se encuentra disponible.\n" +
                    "Verifique que el archivo 'AyudaComprasHelp.chm' exista.",
                    "Ayuda no disponible",
                    JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir la ayuda: " + ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        this.dispose();
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Cerró ventana de mantenimiento de proveedores");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Connection conn = null;
        try {
            conn = Conexion.getConexion();

            if (conn == null) {
                JOptionPane.showMessageDialog(this, "No se pudo establecer conexión con la base de datos.");
                return;
            }

            // Buscar el archivo del reporte en diferentes ubicaciones
            String[] rutasPosibles = {
                "src/main/java/Reportes/ComprayVentas/reporteProveedores.jrxml",
                "src/main/resources/Reportes/ComprayVentas/reporteProveedores.jrxml",
                "Reportes/ComprayVentas/reporteProveedores.jrxml"
            };

            File archivoReporte = null;
            for (String ruta : rutasPosibles) {
                File temp = new File(ruta);
                if (temp.exists()) {
                    archivoReporte = temp;
                    break;
                }
            }

            if (archivoReporte == null || !archivoReporte.exists()) {
                JOptionPane.showMessageDialog(this,
                    "No se encontró el archivo del reporte.\n" +
                    "Verifique que 'reporteProveedores.jrxml' exista en la carpeta de Reportes.");
                return;
            }

            // Compilar y llenar el reporte
            JasperReport jasperReport = JasperCompileManager.compileReport(archivoReporte.getAbsolutePath());
            Map<String, Object> parametros = new HashMap<>();
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);

            // Mostrar el reporte
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setTitle("Reporte de Proveedores");
            viewer.setVisible(true);

            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Generó Reporte de Proveedores");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte de proveedores:\n" + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (conn != null && !conn.isClosed()) {
                    conn.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoCarreras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarr;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtProCodigo;
    private javax.swing.JTextField txtProNit;
    private javax.swing.JTextField txtProNombre;
    // End of variables declaration//GEN-END:variables
}
