/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Carreras;

import Controlador.clsUsuarioConectado;

import Controlador.Carreras.clsCarreras;
import Modelo.Carreras.CarrerasDAO;


import Modelo.BitacoraDAO;
import Modelo.PermisosDAO;

// 3. Importar librerías estándar de Java Swing
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.io.File;

import java.lang.Process;


import java.lang.Runtime;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import Modelo.Conexion;


/**
 *
 * @author 50240
 */
public class frmMantenimientoCarreras extends javax.swing.JFrame {

   CarrerasDAO carrerasDAO = new CarrerasDAO();
    BitacoraDAO bitacoraDAO = new BitacoraDAO();
    PermisosDAO permisosDAO = new PermisosDAO();
    
    private int idUsuarioConectado = clsUsuarioConectado.getUsuId();
    int Aplcodigo = 8087;

    /**
     * Creates new form frmMantenimientoCarreras
     */
    public frmMantenimientoCarreras() {
        initComponents();
        
        // CORRECCIÓN LOCAL: Si no es Admin (ID 1), debe tener permisos mínimos para poder VER el módulo (Buscar)
        if (idUsuarioConectado != 1 && !permisosDAO.puedeBuscar(idUsuarioConectado, Aplcodigo)) {
            JOptionPane.showMessageDialog(null, "No tiene acceso a este módulo para visualizar datos.");
            this.dispose();
            return;
        }
        
        llenarTabla();
        cargarPermisosVisuales();
    }

    // Deshabilita o habilita los botones en la carga inicial según permisos (Solo Lectura dinámico)
    public void cargarPermisosVisuales() {
        btnRegistrar.setEnabled(puedeInsertar());
        btnModificarr.setEnabled(puedeModificar());
        btnEliminar.setEnabled(puedeEliminar());
        btnBuscar.setEnabled(puedeBuscar());
    }

    // Métodos lógicos locales con Bypass integrado para Administrador (ID 1)
    private boolean puedeInsertar() {
        if (idUsuarioConectado == 1) return true;
        return permisosDAO.puedeInsertar(idUsuarioConectado, Aplcodigo);
    }

    private boolean puedeModificar() {
        if (idUsuarioConectado == 1) return true;
        return permisosDAO.puedeModificar(idUsuarioConectado, Aplcodigo);
    }

    private boolean puedeEliminar() {
        if (idUsuarioConectado == 1) return true;
        return permisosDAO.puedeEliminar(idUsuarioConectado, Aplcodigo);
    }

    private boolean puedeBuscar() {
        if (idUsuarioConectado == 1) return true;
        return permisosDAO.puedeBuscar(idUsuarioConectado, Aplcodigo);
    }

    public void llenarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO CARRERA");
        modelo.addColumn("NOMBRE CARRERA");
        modelo.addColumn("CODIGO FACULTAD");
        modelo.addColumn("ESTATUS");
       

        tablaCarreras.setModel(modelo);
        List<clsCarreras> listaCarreras = carrerasDAO.consultaCarreras();

        for (clsCarreras carrera : listaCarreras) {
            modelo.addRow(new Object[]{
                carrera.getcodigo_carrera(),
                carrera.getnombre_carrera(),
                carrera.getcodigo_facultad(),
                carrera.getestatus_carrera(),
                
            });
        }
    }

    public void limpiarCampos() {
        txtProCodigo.setText("");
        txtProNombre.setText("");
        txtProNit.setText("");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarreras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProNombre = new javax.swing.JTextField();
        txtProNit = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificarr = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        txtEstatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        tablaCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO CARRERA", "NOMBRE CARRERA", "CODIGO FACULTAD", "ESTADO"
            }
        ));
        jScrollPane2.setViewportView(tablaCarreras);

        jLabel1.setText("CARRERAS");

        jLabel2.setText("CODIGO CARRERA:");

        jLabel3.setText("NOMBRE CARRERA:");

        jLabel4.setText("CODIGO FACULTAD:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificarr.setText("Modificar");
        btnModificarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarrActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("ESTADO:");

        jButton6.setText("AYUDA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnSalida.setText("SALIR");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEstatus, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtProNit, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(txtProNombre)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificarr)
                            .addComponent(btnEliminar)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtProCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtProNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarr))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtProNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(jLabel8)
                            .addComponent(txtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6)
                                    .addComponent(btnSalida)
                                    .addComponent(btnReportes))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        // VALIDACIÓN DE PERMISO (Incluye Bypass Admin ID 1)
        if (!puedeInsertar()) {
            JOptionPane.showMessageDialog(null, "No posee permisos para registrar carreras.");
            return;
        }

        clsCarreras carrera = new clsCarreras();
        carrera.setnombre_carrera(txtProNombre.getText());
        carrera.setcodigo_facultad(txtProNit.getText());
        carrera.setestatus_carrera(txtEstatus.getText());

        if (carrerasDAO.ingresarCarrera(carrera) > 0) {
            JOptionPane.showMessageDialog(null, "Carrera Registrado con éxito");
            // Registro en bitácora con el ID del usuario actual
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Registró Carrera");
            llenarTabla();
            limpiarCampos();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarrActionPerformed
        // VALIDACIÓN DE PERMISO (Incluye Bypass Admin ID 1)
        if (!puedeModificar()) {
            JOptionPane.showMessageDialog(null, "No posee permisos para modificar información.");
            return;
        }

        if (txtProCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe buscar primero un carrera antes de modificarlo.");
            return;
        }

        clsCarreras carrera = new clsCarreras();
        carrera.setcodigo_carrera(txtProCodigo.getText());
        carrera.setnombre_carrera(txtProNombre.getText());
        carrera.setcodigo_facultad(txtProNit.getText());
        carrera.setestatus_carrera(txtEstatus.getText());

        if (carrerasDAO.actualizarCarrera(carrera) > 0) {
            JOptionPane.showMessageDialog(null, "Información actualizada correctamente");
            // Registro en bitácora
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Modificó Carrera ID: " + txtProCodigo.getText());
            llenarTabla();
            limpiarCampos();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarrActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!puedeEliminar()) {
            JOptionPane.showMessageDialog(null, "No posee permisos para eliminar registros.");
            return;
        }

        if (txtProCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el código del carrera que desea eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este carrera?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacion == 0) {
            clsCarreras carrera = new clsCarreras();
            carrera.setcodigo_carrera(txtProCodigo.getText());

            if (carrerasDAO.borrarCarrera(carrera) > 0) {
                // Registro en bitácora si se eliminó con éxito
                bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Eliminó Carrera ID: " + txtProCodigo.getText());
            }
            llenarTabla();
            limpiarCampos();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!puedeBuscar()) {
            JOptionPane.showMessageDialog(null, "No posee permisos para realizar búsquedas.");
            return;
        }

        if (txtProCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un código para buscar.");
            return;
        }

        clsCarreras carrera = new clsCarreras();
        carrera.setcodigo_carrera(txtProCodigo.getText());
        carrera = carrerasDAO.consultaCarreraPorId(carrera);

        if (carrera.getnombre_carrera() != null) {
            txtProNombre.setText(carrera.getnombre_carrera());
            txtProNit.setText(carrera.getcodigo_facultad());
            txtEstatus.setText(carrera.getestatus_carrera());

            // Registro en bitácora de la consulta realizada
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Buscó Carrera ID: " + txtProCodigo.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Carrera no encontrado");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
        File archivo = new File(
            "src\\main\\java\\Ayudas\\Compras\\AyudaComprasHelp.chm"
        );

        if (!archivo.exists()) {
            JOptionPane.showMessageDialog(
                null,
                "La ayuda no fue encontrada en:\n" + archivo.getAbsolutePath()
            );
            return;
        }

        ProcessBuilder pb = new ProcessBuilder(
            "cmd",
            "/c",
            "start",
            "",
            archivo.getAbsolutePath()
        );

        pb.start();

    } catch (Exception ex) {
        ex.printStackTrace();

        JOptionPane.showMessageDialog(
            null,
            "Error al abrir la ayuda:\n" + ex.getMessage()
        );
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        this.dispose();
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Cerró ventana de mantenimiento de carreraes");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
            try {
        Conexion cn = new Conexion();
        Connection con = cn.getConnection();

        if (con == null) {
            JOptionPane.showMessageDialog(null, "No se pudo conectar a la base de datos.");
            return;
        }

        String rutaReporte = "src\\main\\java\\Reportes\\ComprayVentas\\reporteCompras.jasper";

        Map<String, Object> parametros = new HashMap<>();

        JasperPrint reporte = JasperFillManager.fillReport(
                rutaReporte,
                parametros,
                con
        );

        JasperViewer.viewReport(reporte, false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                null,
                "Error al generar el reporte:\n" + e.getMessage()
        );
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoCarreras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarr;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaCarreras;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtProCodigo;
    private javax.swing.JTextField txtProNit;
    private javax.swing.JTextField txtProNombre;
    // End of variables declaration//GEN-END:variables
}
